#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import getopt
import sys
LOS_FUNC_NO_USE_API = "los_func_no_use_api"
LOS_H = "// This file is automatically generated by los.\n// please do not modify.\n\n"
VERSION = '0.1.0'

out_file_name = "los.ld"
in_file_name = "los_api.h"

los_stack_size = 1024


def main():
    func_num = 0xfff00000
    losld = ""
    file_start = 0
    file = open(in_file_name)
    while 1:
        lines = file.readlines(100000)
        if not lines:
            break
        if(2 == file_start):
            break
        for line in lines:
            if "//los_api_start" in line:
                file_start = 1
                continue
            if "//los_api_end" in line:
                file_start = 2
                break
            if(1 == file_start):
                fname = line.strip().split(",")[0]
                if(len(fname) == 0):
                    continue
                if('/' == fname[0]):
                    continue
                if("0" == fname):
                    fname = LOS_FUNC_NO_USE_API
                losld += "PROVIDE ( " + fname + " = " + hex(func_num) + " );\n"
                func_num += 1
    file.close()
    if(2 == file_start):
        fo = open(out_file_name, "w")
        STACK_STR = "STACK_LEN = " + str(los_stack_size) + ";\n\n"
        fo.write(LOS_H + STACK_STR + losld)
        fo.close()


def usage():
    print("-v \t version " + VERSION)
    print("-h \t help")
    print("-o \t 输出文件名字")
    print("-i \t 输入文件名字")
    print("-stack_size \t stack size")


if __name__ == '__main__':
    opts, args = getopt.getopt(sys.argv[1:], "hio:v", ['help', 'stack_size='])
    for name, value in opts:
        if name in ("-h", "--help"):
            usage()
            exit()
        elif name in ("-v"):
            print("-v \t version "+VERSION)
            exit()
        elif name in ("-o"):
            out_file_name = value
        elif name in ("-i"):
            in_file_name = value
        elif name in ("--stack_size"):
            los_stack_size = value
    main()
